# Generated by Django 5.0.7 on 2025-10-21 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_department_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['affiliate__name', 'name']},
        ),
        migrations.AddField(
            model_name='department',
            name='approval_flow',
            field=models.CharField(choices=[('hod_only', 'HOD Only'), ('hod_hr', 'HOD → HR'), ('hod_hr_ceo', 'HOD → HR → CEO'), ('hod_ceo', 'HOD → CEO')], default='hod_hr', help_text='Defines the approval workflow for leave requests in this department', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.affiliate'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('affiliate', 'name')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
    ]
