# Generated by Django 5.0.7 on 2025-10-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_affiliate_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='department',
            name='affiliate',
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
    ]
