name: leave-management-system
region: nyc1

services:
  - name: backend
    source_dir: /
    github:
      repo: g4Joey/Leave-Request-Management
      branch: main
    run_command: gunicorn leave_management.wsgi:application --bind 0.0.0.0:$PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /
    routes:
      - path: /api
    envs:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "leave_management.settings_production"
      - key: SECRET_KEY
        type: SECRET
        value: "prod-secret-key-2025-leave-mgmt-a8f7b2e9c1d4f6h8j3k5m7n9p0q2r4t6"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        type: SECRET
        value: "mysql://doadmin:PLACEHOLDER_PASSWORD@db-mysql-nyc3-43467-do-user-24806705-0.k.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://takeabreak-app-38abv.ondigitalocean.app"

databases:
  - name: db
    engine: MYSQL
    version: "8"
    size: basic-xs
    num_nodes: 1

static_sites:
  - name: frontend
    source_dir: /frontend
    github:
      repo: g4Joey/Leave-Request-Management
      branch: main
    build_command: npm install && npm run build
    output_dir: build
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: "https://takeabreak-app-38abv.ondigitalocean.app/api"