name: takeabreak-app
region: nyc1

services:
  - name: frontend
    source_dir: ./frontend
    github:
      repo: g4Joey/Leave-Request-Management
      branch: main
      deploy_on_push: true
    
    build_command: |
      npm ci
      npm run build
    
    run_command: npx serve -s build -p $PORT
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    envs:
      - key: REACT_APP_API_URL
        value: "https://takeabreak-app-38abv.ondigitalocean.app/api"
      - key: REACT_APP_SHOW_DEMO_LOGINS
        value: "false"
      - key: NODE_ENV
        value: "production"
      - key: GENERATE_SOURCEMAP
        value: "false"

  - name: backend
    source_dir: ./
    github:
      repo: g4Joey/Leave-Request-Management
      branch: main
      deploy_on_push: true
    
    # Hardened run sequence: no automatic seeding; explicit DB verification.
    # If you need initial seeding, deploy first then run manually:
    #   python manage.py setup_production_data
    run_command: |
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py verify_db
      gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT leave_management.wsgi:application
    
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /api
      - path: /admin
      # Backend should not claim / or /static; frontend serves those
    
    envs:
      # Core Django settings
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "leave_management.settings_production"
      - key: SECRET_KEY
        value: "REPLACE_ME_IN_DASHBOARD"  # Set as SECRET in dashboard before deploy
        type: SECRET
      
      # Hosts / CORS (ensure domain consistency)
      - key: ALLOWED_HOSTS
        value: "takeabreak-app-38abv.ondigitalocean.app,127.0.0.1,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://takeabreak-app-38abv.ondigitalocean.app"
      
      # Database configuration (prefer DATABASE_URL; keep placeholders out of repo)
      - key: DATABASE_URL
        value: "mysql://USER:PASSWORD@HOST:25060/leave_management?ssl-mode=REQUIRED"  # Set real secret value in dashboard
        type: SECRET
      # (Optional) Uncomment individual vars instead of DATABASE_URL
      # - key: DB_HOST
      #   value: "private-db-mysql-..."
      # - key: DB_PORT
      #   value: "25060"
      # - key: DB_NAME
      #   value: "leave_management"
      # - key: DB_USER
      #   value: "g4joey"
      # - key: DB_PASSWORD
      #   value: "REPLACE_DB_PASSWORD"
      #   type: SECRET

      # (Optional) Seeding / superuser vars only if doing one-time provisioning
      # - key: DJANGO_SUPERUSER_USERNAME
      #   value: "admin@company.com"
      # - key: DJANGO_SUPERUSER_EMAIL
      #   value: "admin@company.com"
      # - key: DJANGO_SUPERUSER_PASSWORD
      #   value: "REPLACE_SUPERUSER_PASSWORD"
      #   type: SECRET
      # - key: DJANGO_SUPERUSER_EMPLOYEE_ID
      #   value: "ADMIN001"
      # - key: SEED_USERS
      #   value: "<JSON array>"
      #   type: SECRET
      # - key: HR_ADMIN_USERNAME
      #   value: "hradmin@example.com"
      # - key: HR_ADMIN_PASSWORD
      #   value: "REPLACE_HR_PASSWORD"
      #   type: SECRET
      # - key: HR_ADMIN_FIRST_NAME
      #   value: "HR"
      # - key: HR_ADMIN_LAST_NAME
      #   value: "Administrator"
      # - key: HR_ADMIN_EMPLOYEE_ID
      #   value: "HR001"