name: takeabreak-app
region: nyc1

services:
  - name: frontend
    source_dir: ./frontend
    github:
      repo: g4Joey/Leave-Request-Management
      branch: main
      deploy_on_push: true
    
    build_command: |
      npm ci
      npm run build
    
    run_command: npx serve -s build -p $PORT
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    envs:
      - key: REACT_APP_API_URL
        value: "https://takeabreak-app-38abv.ondigitalocean.app/api"
      - key: REACT_APP_SHOW_DEMO_LOGINS
        value: "false"
      - key: NODE_ENV
        value: "production"
      - key: GENERATE_SOURCEMAP
        value: "false"

  - name: backend
    source_dir: ./
    github:
      repo: g4Joey/Leave-Request-Management
      branch: main
      deploy_on_push: true
    
    # Hardened run sequence: removed automatic seeding; explicit DB verification.
    # To seed (only if needed) after first deploy:
    #   python manage.py setup_production_data
    run_command: |
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      # Optionally run idempotent production/data seeding if explicitly enabled.
      if [ "$RUN_SEED_ON_DEPLOY" = "1" ]; then
        echo "RUN_SEED_ON_DEPLOY=1 -> executing setup_production_data (idempotent)";
        python manage.py setup_production_data || { echo "setup_production_data failed"; exit 1; };
      else
        echo "Skipping setup_production_data (RUN_SEED_ON_DEPLOY not set to 1)";
      fi
      # Always ensure leave data is properly set up for leave requests to work
      python manage.py setup_production_leave_data
      python manage.py verify_db
      gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT leave_management.wsgi:application
    
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /api
      - path: /admin
      # Backend should not claim / or /static; frontend serves those
    
    envs:
      # Preserving existing encrypted/production values as requested.
      - key: DEBUG
        value: "False"
        type: SECRET
      - key: DJANGO_SETTINGS_MODULE
        value: "leave_management.settings_production"
      - key: SECRET_KEY
        value: "EV[1:raV6cTECY53b4Ml4DHfKwlTYfvuRO97k:EcMTynELNDUUTF+7hS+IZZNsnTe5VetHCK9fE32V41GHvLE34BCNEaeu1TZYGmveoNdEct7o4KiwtjDoo53xqa8BxLj+h21kiU0g6bBA+IDAfL5p4N4AidcwTu/IEGCoblK+]"
        type: SECRET
      - key: ALLOWED_HOSTS
        value: "takeabreak-app-38abv.ondigitalocean.app,127.0.0.1,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://takeabreak-app-38abv.ondigitalocean.app"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin@company.com"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@company.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "EV[1:JmMu7dLmah5xilEycKUd2TnZio/Kn9f0:KWhjS4NuBuaUrbEIrlT/Qwl86hfkO52+9mYzOLAJU+k=]"
        type: SECRET
      - key: DJANGO_SUPERUSER_EMPLOYEE_ID
        value: "ADMIN001"
      - key: SEED_USERS
        value: "EV[1:aU4rIfuELla8S2cNWPfO8fGT3d2Gl/Qo:wbhmnm4ertHkzJwn1O6ecuA0a5K1P0Cyi4VB4jOrXwz6R8XoIuRW34KaOAJYlTcSZkyPheTlJdXActM4dG6hv7QdPNwjGjnLGBce6rIsS9lv6r/Zo0QieIvFZZfR1aLk78QvD6dSKfNiZEZjaRObWtxM+tLIUrVkT2Ry4j8inOmvgoIOIMXhjcC7eHcrbhhPSt60UobCETnUDB+qcu9yQvNIzmiHaFgFTEKm/ybnwkdad+VEtZT6h6oy8NhefuC84nLxuICE/Uac8iTCRkpvAQB6Sjr9khAUzey4iKgprnOTzggQcBOPuFjdW7y6xItEikAhgNwGFAeabbLH1Aw7Epgtjc4qPUkYJWx69QL7RCSnnMGeFmyhPs/eTAIso3aFL3v+j5ZU4LA2WpqXUCv9g9P/fKVRSlgQIZx+9IQT60cP4FRo3PdtUByoio22U8XnCouc7VgFDJ/Xwdf+obwaa5YIxZ0NNtSKPMlEfibAJXbxxelT7bVXOvHB7hs9YMqI5X0oDAW/NNXVTQs5WI7kBvDIZ4gbBil7PcyzuaXfBubWucbc7SR1l19r813X9+gh629Itj7qiHMDn/b9SE0itz28F7xbaKnRuW7BHgOJguJZDaZFQFoKAOBRhnQi1VYACiSd1WL4VdDzeI6BilPGP6lj89J9AyztxUe55HWJJch1kDrOFCk9U6y1t0WMovPVKvNekfkIKNtpTBDRCjrx/ocwn7eXJlAgvhJxLEBGbtxMnPR1SVrrp6eEVKhop/jeq4AFnq79/NYft3PRMdxaDaz/LuyJ86/c2153shZHT8ocoypZwVgHpBksazDscLOJhBZ4EZE=]"
        type: SECRET
      - key: HR_ADMIN_USERNAME
        value: "hradmin@umbcapital.com"
      - key: HR_ADMIN_PASSWORD
        value: "EV[1:bIk0a488QRvqXkc+pTDpedsTBPWAHiPU:94DDCDfOrNvXXiaRvgblUvaSSTdWPv+S]"
        type: SECRET
      - key: HR_ADMIN_FIRST_NAME
        value: "Joshua"
      - key: HR_ADMIN_LAST_NAME
        value: "Azu"
      - key: HR_ADMIN_EMPLOYEE_ID
        value: "HR001"
      # Database credentials removed from spec per request (new ones configured externally).
      - key: RUN_SEED_ON_DEPLOY
        value: "0"
        # Set to "1" for a single deploy to (re)create / sync seeded users (superuser, HR, Ato, George, Augustine, etc.)
        # Safe & idempotent: will not overwrite existing user passwords.