# Generated by Django 5.0.7 on 2025-11-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leaverequest_ceo_approval_comments_and_more'),
    ]

    operations = [
        # Add database indexes for overlap detection performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS leaves_leaverequest_start_date_idx ON leaves_leaverequest (start_date);",
            reverse_sql="DROP INDEX IF EXISTS leaves_leaverequest_start_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS leaves_leaverequest_end_date_idx ON leaves_leaverequest (end_date);",
            reverse_sql="DROP INDEX IF EXISTS leaves_leaverequest_end_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS leaves_leaverequest_overlap_idx ON leaves_leaverequest (start_date, end_date, status);",
            reverse_sql="DROP INDEX IF EXISTS leaves_leaverequest_overlap_idx;"
        ),
    ]
