# Generated by Django 5.0.7 on 2025-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_auto_20251102_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Manager Approval'), ('manager_approved', 'Manager Approved - Pending HR'), ('hr_approved', 'HR Approved - Pending CEO'), ('ceo_approved', 'CEO Approved - Pending HR'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
