# Generated by Django 5.2.6 on 2025-12-07 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_alter_leaverequest_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='actual_resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interrupted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interrupted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interruptions_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interruption_credited_days',
            field=models.PositiveIntegerField(default=0, help_text='Working days credited back due to recall/early return'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interruption_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LeaveInterruptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('manager_recall', 'Manager Recall'), ('staff_return', 'Staff Early Return')], max_length=20)),
                ('status', models.CharField(choices=[('pending_staff', 'Pending Staff Response'), ('pending_manager', 'Pending Manager Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_staff', max_length=20)),
                ('requested_resume_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('initiated_role', models.CharField(blank=True, default='', max_length=20)),
                ('manager_decision_at', models.DateTimeField(blank=True, null=True)),
                ('manager_decision_comment', models.TextField(blank=True, default='')),
                ('hr_decision_at', models.DateTimeField(blank=True, null=True)),
                ('hr_decision_comment', models.TextField(blank=True, default='')),
                ('staff_decision_at', models.DateTimeField(blank=True, null=True)),
                ('staff_decision_comment', models.TextField(blank=True, default='')),
                ('credited_working_days', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrupts_hr_decisions', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrupts_initiated', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrupt_requests', to='leaves.leaverequest')),
                ('manager_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrupts_manager_decisions', to=settings.AUTH_USER_MODEL)),
                ('staff_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrupts_staff_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveInterruptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('requested', 'Requested'), ('staff_accepted', 'Staff Accepted'), ('staff_rejected', 'Staff Rejected'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('applied', 'Applied')], max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('credited_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrupt_logs', to='leaves.leaverequest')),
                ('interrupt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='leaves.leaveinterruptrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveResumeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_events', to='leaves.leaverequest')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
