# Generated by Django 5.0.7 on 2025-11-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Additional notification metadata (e.g., overlap details, links)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_submitted', 'Leave Request Submitted'), ('leave_manager_approved', 'Leave Request Approved by Manager'), ('leave_hr_approved', 'Leave Request Approved by HR'), ('leave_approved', 'Leave Request Fully Approved'), ('leave_rejected', 'Leave Request Rejected'), ('leave_cancelled', 'Leave Request Cancelled'), ('leave_overlap_detected', 'Leave Overlap Detected'), ('balance_low', 'Leave Balance Low'), ('system', 'System Notification')], max_length=30),
        ),
    ]
